---
title: "Identifying Fraud from Enron Email"
author: "Jay"
date: "Tuesday, July 21, 2015"
output: html_document
---

```{r}
setwd('C:\\Users\\Jay\\Docker\\nanodegree\\project6\\final_project')
df = read.csv('dataset.csv')

# Transpose (no longer used)
# n <- df$X
# df <- as.data.frame(t(df[,-1]))
# colnames(df) <- n

transform_and_plot_df <- function(df) {
  df <- transform(df,
                  name = as.character(name),
                  bonus = as.numeric(as.character(bonus)),
                  deferral_payments = as.numeric(as.character(deferral_payments)),
                  deferred_income = as.numeric(as.character(deferred_income)),
                  director_fees = as.numeric(as.character(director_fees)),
                  exercised_stock_options = as.numeric(as.character(exercised_stock_options)),
                  expenses = as.numeric(as.character(expenses)),
                  total_payments = as.numeric(as.character(total_payments)),
                  total_stock_value = as.numeric(as.character(total_stock_value)),
                  from_messages = as.numeric(as.character(from_messages)),
                  from_poi_to_this_person = as.numeric(as.character(from_poi_to_this_person)),
                  from_this_person_to_poi = as.numeric(as.character(from_this_person_to_poi)),
                  loan_advances = as.numeric(as.character(loan_advances)),
                  long_term_incentive = as.numeric(as.character(long_term_incentive)),
                  other = as.numeric(as.character(other)),
                  restricted_stock = as.numeric(as.character(restricted_stock)),
                  restricted_stock_deferred = as.numeric(as.character(restricted_stock_deferred)),
                  salary = as.numeric(as.character(salary)),
                  shared_receipt_with_poi = as.numeric(as.character(shared_receipt_with_poi)),
                  to_messages = as.numeric(as.character(to_messages)),
                  poi = as.logical(poi)
                  )
  pair <- data.frame(
    bonus = df$bonus,
    deferral_payments = df$deferral_payments,
    deferred_income = df$deferred_income,
    director_fees = df$director_fees,
    exercised_stock_options = df$exercised_stock_options,
    expenses = df$expenses,
    total_payments = df$total_payments,
    total_stock_value = df$total_stock_value,
    from_messages = df$from_messages,
    from_poi_to_this_person = df$from_poi_to_this_person,
    from_this_person_to_poi = df$from_this_person_to_poi,
    loan_advances = df$loan_advances,
    long_term_incentive = df$long_term_incentive,
    other = df$other,
    restricted_stock = df$restricted_stock,
    restricted_stock_deferred = df$restricted_stock_deferred,
    salary = df$salary,
    shared_receipt_with_poi = df$shared_receipt_with_poi,
    to_messages = df$to_messages,
    poi = df$poi)
  pair[is.na(pair)] <- 0 
  corrplot(cor(pair), method = "number")
}
```
```{r}
library(ggplot2)
library(GGally)
library(corrplot)
```

```{r}
ggplot(aes(x=bonus),data=df) + geom_histogram()
```

```{r}
ggplot(aes(x=deferral_payments),data=df) + geom_histogram()
```

```{r corrplot_w_outliers, fig.width=10, fig.height=10, cache=TRUE, cache.path = 'cache/', fig.path='figure/'}
transform_and_plot_df(df)
```
```{r corrplot_updated, fig.width=10, fig.height=10, cache=TRUE, cache.path = 'cache/', fig.path='figure/'}
df2 = read.csv('dataset_updated.csv')
transform_and_plot_df(df2)
```